# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"
  httpcheck/frontendproxy:
    targets:
      - endpoint: http://robot-shop-web-1:${env:ENVOY_PORT}
  prometheus:
    config:
      scrape_configs:
        - job_name: rabbitmq
          scrape_interval: 1s
          static_configs:
            - targets: [rabbitmq:15692]
        - job_name: redis-exporter
          scrape_interval: 1s
          static_configs:
            - targets: [redis-exporter:9121]
        - job_name: mongodb-exporter
          scrape_interval: 1s
          static_configs:
            - targets: [mongodb-exporter:9216]
  mongodb:
    hosts:
      endpoint: "mongodb://mongo-database:27017"
    tls:
      insecure: true
      insecure_skip_verify: true
          

exporters:
  debug:
  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
    resource_to_telemetry_conversion:
      enabled: true

processors:
  batch:

connectors:
  spanmetrics:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, debug, spanmetrics]
    metrics:
      receivers: [httpcheck/frontendproxy, otlp, spanmetrics,prometheus,mongodb]
      processors: [batch]
      exporters: [prometheus, debug]
